    name: CI-CD Pipeline
    env:
      ARTIFACT_NAME: csye6225-webapp-${{ github.sha }}.zip
      CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
      CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: csye6225-webapp-deployment
      AWS_REGION: us-east-1
    on:
      pull_request:
        branches:
        - main
        - master
    jobs:
      ci_cd:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}
        
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        
        - name: Build with Maven
          run: cd CloudNativeWebApp && mvn -N io.takari:maven:wrapper && ./mvnw clean install
        
        - name: Build Deployment Artifact
          run: |
            mkdir codedeploy_artifact
            zip -r ${{ env.ARTIFACT_NAME }} CloudNativeWebApp/target/CloudNativeWebApp-0.0.1-SNAPSHOT.jar codedeploy/*.sh appspec.yml
            mv ${{ env.ARTIFACT_NAME }} codedeploy_artifact/

        
          
        
        - name: Copy Artifact to S3
          run: |
            aws s3 sync ./codedeploy_artifact s3://codedeploy.6225csyekeyuliu.me.prod

        - name: CodeDeploy API call
          run: |
              output=$(aws deploy create-deployment --application-name ${{env.CODEDEPLOY_APPLICATION_NAME}} --deployment-group-name ${{env.CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME}} --s3-location bucket=${{secrets.S3_CODEDEPLOY_BUCKET}},bundleType=zip,key=webapp.zip --region ${{env.AWS_REGION }} --output json)

              echo $output

              dId=$(echo $output | jq -r '.deploymentId')

              aws deploy wait deployment-successful --deployment-id $dId
            




